# Generated by Django 3.1.2 on 2022-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attadence_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
